services:
  ml-inference:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_inference
    networks:
      - inference-backend
    environment:
      DB_HOST: wardrobe-postgres
      DB_PORT: 5434
      DB_NAME: wardrobe_db
      DB_USER: admin
      DB_PASSWORD: admin
      REDIS_URL: redis://redis:16379/0
      ML_TASKS_QUEUE: ml_tasks
      ML_TASKS_DLQ: ml_tasks_dlq
      EMBEDDING_DIM: 512
      OPENCLIP_PRETRAINED: openai
      PYTHONPATH: /app/src
      OPENCLIP_MODEL_NAME: ViT-B-32
      INFERENCE_DEVICE: cpu

networks:
  inference-backend:
    driver: bridge
